version: "3"
services:
  backend:
    build: ./server
    command: python3 ./server/app/main.py
    volumes:
      - .:/server
    ports:
      - "8000:8000"
  frontend:
    build: ./client
    command: npm run start
    volumes:
      - .:/client
    ports:
      - "80:3000"
